using Entities.Enums;

namespace Logging;

/// <summary>
/// Attribute for specifying log category generated by class
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, AllowMultiple = false, Inherited = true)]
public class LogCategoryAttribute : Attribute
{
    /// <summary>
    /// Log category for class
    /// </summary>
    public LogCategory Category { get; }

    /// <summary>
    /// Attribute constructor
    /// </summary>
    /// <param name="category">Log category</param>
    public LogCategoryAttribute(LogCategory category) {
        Category = category;
    }
}
